=== copton/lethe/extensions/types/Complex/instances/Complex.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--generated at: 2006-04-16T21:05:58.273+02:00-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:simmit="https://proj.5nord.org/simmit"
        xmlns:self="https://proj.5nord.org/simmit/types/Complex"
        targetNamespace="https://proj.5nord.org/simmit/types/Complex">
   <import namespace="https://proj.5nord.org/simmit"
           schemaLocation="../../../../core/xml/moduleParameter.xsd"/>
   <element name="Complex">
      <complexType>
         <sequence>
            <group ref="self:headerSet"/>
            <element name="include" type="self:include"/>
            <element name="export" type="self:Complex"/>
         </sequence>
         <attribute name="imprints" type="string"/>
      </complexType>
   </element>
   <group name="headerSet">
      <sequence>
         <element minOccurs="0" name="author" type="string"/>
         <element minOccurs="0" name="version" type="string"/>
         <element minOccurs="0" name="date" type="date"/>
         <element minOccurs="0" name="description" type="string"/>
      </sequence>
   </group>
   <complexType name="include">
      <all/>
   </complexType>
   <complexType name="Complex">
      <all>
         <element name="real" type="simmit:double"/>
         <element name="img" type="simmit:double"/>
      </all>
      <attribute fixed="class" name="type"/>
      <attribute default="" name="description"/>
      <attribute fixed="Complex" name="classname"/>
   </complexType>
   <complexType name="TestClass">
      <sequence>
         <element maxOccurs="unbounded" minOccurs="0" name="field">
            <complexType>
               <simpleContent>
                  <extension base="integer">
                     <attribute name="pos" type="integer"/>
                     <attribute name="type" fixed="int"/>
                  </extension>
               </simpleContent>
            </complexType>
         </element>
      </sequence>
      <attribute fixed="array" name="type"/>
      <attribute default="" name="description"/>
      <attribute fixed="TestClass" name="classname"/>
      <attribute fixed="int" name="elementType"/>
   </complexType>
</schema>

=== copton/lethe/extensions/types/Complex/instances/Complex.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--generated at: 2006-04-16T21:05:58.154+02:00-->
<type:Complex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:type="https://proj.5nord.org/simmit/types/Complex"
              xsi:schemaLocation="https://proj.5nord.org/simmit/types/Complex Complex.xsd"
              imprints="Complex2">
   <author>phia</author>
   <version>1.0</version>
   <description>Klasse fuer komplexe Zahlen</description>
   <include/>
   <export type="class" classname="Complex">
      <real type="double">0</real>
      <img type="double">0</img>
   </export>
</type:Complex>
