=== copton/lethe/extensions/modules/Encoder/instances/Encoder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--generated at: 2006-04-17T19:04:22.987+02:00-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:simmit="https://proj.5nord.org/simmit"
        xmlns:self="https://proj.5nord.org/simmit/modules/Encoder"
        targetNamespace="https://proj.5nord.org/simmit/modules/Encoder">
   <import namespace="https://proj.5nord.org/simmit"
           schemaLocation="../../../../core/xml/moduleDescription.xsd"/>
   <element name="Encoder">
      <complexType>
         <sequence>
            <group ref="self:headerSet"/>
            <element name="include" type="self:include"/>
            <element name="parameter" type="self:parameter"/>
            <element name="ports" type="self:portList"/>
         </sequence>
      </complexType>
   </element>
   <group name="headerSet">
      <sequence>
         <element minOccurs="0" name="author" type="string"/>
         <element minOccurs="0" name="version" type="string"/>
         <element minOccurs="0" name="date" type="date"/>
         <element minOccurs="0" name="type" type="string"/>
         <element minOccurs="0" name="description" type="string"/>
      </sequence>
   </group>
   <complexType name="include">
      <all/>
   </complexType>
   <complexType name="parameter">
      <all>
         <element name="configuration" type="self:configuration"/>
         <element name="settings" type="self:settings"/>
      </all>
   </complexType>
   <complexType name="portList">
      <all>
         <element name="Input" type="simmit:inputPort"/>
         <element name="Output" type="simmit:outputPort"/>
      </all>
   </complexType>
   <complexType name="configuration">
      <all/>
   </complexType>
   <complexType name="settings">
      <all>
         <element name="amplifier" type="simmit:int"/>
      </all>
   </complexType>
</schema>

=== copton/lethe/extensions/modules/Encoder/instances/Encoder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--generated at: 2006-04-17T19:04:22.861+02:00-->
<module:Encoder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:module="https://proj.5nord.org/simmit/modules/Encoder"
                xsi:schemaLocation="https://proj.5nord.org/simmit/modules/Encoder Encoder.xsd">
   <author>alex</author>
   <version>1.0</version>
   <date>2006-03-06</date>
   <type>Kodierer</type>
   <description/>
   <include/>
   <parameter>
      <configuration/>
      <settings>
         <amplifier type="int">0</amplifier>
      </settings>
   </parameter>
   <ports>
      <Input direction="input" type="Integer" blocksize="2" usedType="" description=""/>
    
      <Output direction="output" type="Complex" blocksize="1" usedType="" description=""/>
    </ports>
</module:Encoder>
