=== copton/lethe/core/xml/examples/testJob.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:simmit="https://proj.5nord.org/simmit"
        xmlns:Source="https://proj.5nord.org/simmit/modules/Source"
        xmlns:Encoder="https://proj.5nord.org/simmit/modules/Encoder"
        xmlns:Channel="https://proj.5nord.org/simmit/modules/Channel"
        xmlns:Decoder="https://proj.5nord.org/simmit/modules/Decoder"
        xmlns:Sink="https://proj.5nord.org/simmit/modules/Sink"
        targetNamespace="https://proj.5nord.org/simmit">
   <import namespace="https://proj.5nord.org/simmit/modules/Source"
           schemaLocation="/home/alex/diplomarbeit/svnroot/trunk/code/extensions/modules/Source/instances/Source.xsd"/>
   <import namespace="https://proj.5nord.org/simmit/modules/Encoder"
           schemaLocation="/home/alex/diplomarbeit/svnroot/trunk/code/extensions/modules/Encoder/instances/Encoder.xsd"/>
   <import namespace="https://proj.5nord.org/simmit/modules/Channel"
           schemaLocation="/home/alex/diplomarbeit/svnroot/trunk/code/extensions/modules/Channel/instances/Channel.xsd"/>
   <import namespace="https://proj.5nord.org/simmit/modules/Decoder"
           schemaLocation="/home/alex/diplomarbeit/svnroot/trunk/code/extensions/modules/Decoder/instances/Decoder.xsd"/>
   <import namespace="https://proj.5nord.org/simmit/modules/Sink"
           schemaLocation="/home/alex/diplomarbeit/svnroot/trunk/code/extensions/modules/Sink/instances/Sink.xsd"/>
   <include schemaLocation="/home/alex/diplomarbeit/svnroot/trunk/code/core/xml/moduleDescription.xsd"/>
   <element name="job">
      <complexType>
         <sequence>
            <group ref="simmit:headerInformationWithName"/>
            <element name="graph" type="simmit:graph"/>
            <element name="settings" type="simmit:job_settings"/>
         </sequence>
      </complexType>
   </element>
   <complexType name="graph">
      <sequence>
         <element name="nodes" type="simmit:nodes"/>
         <element name="edges" type="simmit:edges"/>
         <element name="phases" type="simmit:phases"/>
      </sequence>
   </complexType>
   <complexType name="nodes">
      <all>
         <element name="node">
            <complexType>
               <sequence>
                  <element fixed="Quelle" name="name"/>
                  <element name="location">
                     <complexType>
                        <sequence>
                           <element fixed="Source" name="module"/>
                           <element name="instance" type="string"/>
                        </sequence>
                     </complexType>
                  </element>
                  <element minOccurs="0" name="configuration">
                     <complexType>
                        <all>
                           <element minOccurs="0" name="useRandom" type="simmit:boolean"/>
                        </all>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
         <element name="node">
            <complexType>
               <sequence>
                  <element fixed="Kodierer" name="name"/>
                  <element name="location">
                     <complexType>
                        <sequence>
                           <element fixed="Encoder" name="module"/>
                           <element name="instance" type="string"/>
                        </sequence>
                     </complexType>
                  </element>
                  <element minOccurs="0" name="configuration">
                     <complexType>
                        <all/>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
         <element name="node">
            <complexType>
               <sequence>
                  <element fixed="Kanal" name="name"/>
                  <element name="location">
                     <complexType>
                        <sequence>
                           <element fixed="Channel" name="module"/>
                           <element name="instance" type="string"/>
                        </sequence>
                     </complexType>
                  </element>
                  <element minOccurs="0" name="configuration">
                     <complexType>
                        <all/>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
         <element name="node">
            <complexType>
               <sequence>
                  <element fixed="Dekodierer" name="name"/>
                  <element name="location">
                     <complexType>
                        <sequence>
                           <element fixed="Decoder" name="module"/>
                           <element name="instance" type="string"/>
                        </sequence>
                     </complexType>
                  </element>
                  <element minOccurs="0" name="configuration">
                     <complexType>
                        <all/>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
         <element name="node">
            <complexType>
               <sequence>
                  <element fixed="Senke" name="name"/>
                  <element name="location">
                     <complexType>
                        <sequence>
                           <element fixed="Sink" name="module"/>
                           <element name="instance" type="string"/>
                        </sequence>
                     </complexType>
                  </element>
                  <element minOccurs="0" name="configuration">
                     <complexType>
                        <all>
                           <element minOccurs="0" name="abort" type="simmit:int"/>
                           <element minOccurs="0" name="counter" type="simmit:int"/>
                        </all>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
      </all>
   </complexType>
   <complexType name="edges">
      <sequence>
         <element minOccurs="0" name="edge">
            <complexType>
               <sequence>
                  <element fixed="quelle2kodierer" name="name"/>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Quelle" name="name"/>
                           <element fixed="Output" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="output" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Kodierer" name="name"/>
                           <element fixed="Input" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="input" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Senke" name="name"/>
                           <element fixed="Source" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="input" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
         <element minOccurs="0" name="edge">
            <complexType>
               <sequence>
                  <element fixed="kodierer2kanal" name="name"/>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Kodierer" name="name"/>
                           <element fixed="Output" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="output" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Kanal" name="name"/>
                           <element fixed="Input" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="input" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
         <element minOccurs="0" name="edge">
            <complexType>
               <sequence>
                  <element fixed="kanal2decoder" name="name"/>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Kanal" name="name"/>
                           <element fixed="Output" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="output" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Dekodierer" name="name"/>
                           <element fixed="Input" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="input" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
         <element minOccurs="0" name="edge">
            <complexType>
               <sequence>
                  <element fixed="dekodierer2senke" name="name"/>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Dekodierer" name="name"/>
                           <element fixed="Output" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="output" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
                  <element name="node">
                     <complexType>
                        <sequence>
                           <element fixed="Senke" name="name"/>
                           <element fixed="Result" name="port">
                              <complexType>
                                 <simpleContent>
                                    <extension base="string">
                                       <attribute fixed="input" name="direction"/>
                                    </extension>
                                 </simpleContent>
                              </complexType>
                           </element>
                        </sequence>
                     </complexType>
                  </element>
               </sequence>
            </complexType>
         </element>
      </sequence>
   </complexType>
   <complexType name="phases">
      <sequence>
         <element maxOccurs="unbounded" name="phase">
            <complexType>
               <sequence>
                  <element maxOccurs="unbounded" name="node">
                     <complexType>
                        <sequence>
                           <element name="name">
                              <simpleType>
                                 <restriction base="string">
                                    <enumeration value="Quelle"/>
                                    <enumeration value="Kodierer"/>
                                    <enumeration value="Kanal"/>
                                    <enumeration value="Dekodierer"/>
                                    <enumeration value="Senke"/>
                                 </restriction>
                              </simpleType>
                           </element>
                           <element minOccurs="0" name="observed">
                              <complexType/>
                           </element>
                           <sequence>
                              <element maxOccurs="unbounded" minOccurs="0" name="port">
                                 <complexType>
                                    <sequence>
                                       <element name="name" type="string"/>
                                       <element minOccurs="0" name="reset">
                                          <complexType/>
                                       </element>
                                    </sequence>
                                 </complexType>
                              </element>
                           </sequence>
                        </sequence>
                     </complexType>
                  </element>
               </sequence>
               <attribute name="nr" type="integer"/>
            </complexType>
         </element>
      </sequence>
   </complexType>
   <complexType name="job_settings">
      <sequence>
         <element name="default">
            <complexType>
               <sequence>
                  <element maxOccurs="unbounded" minOccurs="0" name="node" type="simmit:availableNodes"/>
               </sequence>
            </complexType>
         </element>
         <element name="rounds">
            <complexType>
               <sequence>
                  <element minOccurs="0" name="description" type="string"/>
                  <element maxOccurs="5" minOccurs="0" name="round">
                     <complexType>
                        <sequence>
                           <element minOccurs="0" name="description" type="string"/>
                           <element maxOccurs="unbounded" minOccurs="0" name="node" type="simmit:availableNodes"/>
                        </sequence>
                        <attribute name="nr">
                           <simpleType>
                              <restriction base="integer">
                                 <minInclusive value="1"/>
                                 <maxInclusive value="5"/>
                              </restriction>
                           </simpleType>
                        </attribute>
                     </complexType>
                  </element>
               </sequence>
               <attribute fixed="5" name="anz"/>
            </complexType>
         </element>
      </sequence>
   </complexType>
   <complexType name="availableNodes">
      <choice>
         <sequence>
            <element name="name">
               <simpleType>
                  <restriction base="string">
                     <enumeration value="Quelle"/>
                  </restriction>
               </simpleType>
            </element>
            <element minOccurs="0" name="newSeed" type="simmit:boolean"/>
            <element minOccurs="0" name="seed" type="simmit:long"/>
         </sequence>
         <sequence>
            <element name="name">
               <simpleType>
                  <restriction base="string">
                     <enumeration value="Kodierer"/>
                  </restriction>
               </simpleType>
            </element>
            <element minOccurs="0" name="amplifier" type="simmit:int"/>
         </sequence>
         <sequence>
            <element name="name">
               <simpleType>
                  <restriction base="string">
                     <enumeration value="Kanal"/>
                  </restriction>
               </simpleType>
            </element>
            <element minOccurs="0" name="noiseReal" type="Channel:Noise"/>
            <element minOccurs="0" name="noiseImag" type="Channel:Noise"/>
         </sequence>
         <sequence>
            <element name="name">
               <simpleType>
                  <restriction base="string">
                     <enumeration value="Dekodierer"/>
                  </restriction>
               </simpleType>
            </element>
         </sequence>
         <sequence>
            <element name="name">
               <simpleType>
                  <restriction base="string">
                     <enumeration value="Senke"/>
                  </restriction>
               </simpleType>
            </element>
         </sequence>
      </choice>
   </complexType>
</schema>

=== copton/lethe/core/xml/examples/testJob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--TODO: phases fehlen noch, und statt import moduleDescription.xsd muss es include heissen! -->
<simmit:job xmlns:simmit="https://proj.5nord.org/simmit" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://proj.5nord.org/simmit testJob.xsd"> 
	<name>Testmodul</name>
	<author>phia</author>
	<version>0.1</version>
	<date>2006-01-14</date>
	<description>Einfacher Graph</description>
	<graph>
		<nodes>
			<node>
				<name>Quelle</name>
				<location>
					<module>Source</module>
					<instance>Source</instance>
				</location>
			</node>
			<node>
				<name>Kodierer</name>
				<location>
					<module>Encoder</module>
					<instance>Encoder</instance>
				</location>
			</node>
			<node>
				<name>Kanal</name>
				<location>
					<module>Channel</module>
					<instance>Channel</instance>
				</location>
			</node>
			<node>
				<name>Dekodierer</name>
				<location>
					<module>Decoder</module>
					<instance>Decoder</instance>
				</location>
			</node>
			<node>
				<name>Senke</name>
				<location>
					<module>Sink</module>
					<instance>Sink</instance>
				</location>
			</node>
		</nodes>
		<edges>
			<edge>
				<name>quelle2kodierer</name>
				<node>
					<name>Quelle</name>
					<port>Output</port>
				</node>
				<node>
					<name>Kodierer</name>
					<port>Input</port>
				</node>
				<node>
					<name>Senke</name>
					<port>Source</port>
				</node>
			</edge>
			<edge>
				<name>kodierer2kanal</name>
				<node>
					<name>Kodierer</name>
					<port>Output</port>
				</node>
				<node>
					<name>Kanal</name>
					<port>Input</port>
				</node>
			</edge>
			<edge>
				<name>kanal2decoder</name>
				<node>
					<name>Kanal</name>
					<port>Output</port>
				</node>
				<node>
					<name>Dekodierer</name>
					<port>Input</port>
				</node>
			</edge>
			<edge>
				<name>dekodierer2senke</name>
				<node>
					<name>Dekodierer</name>
					<port>Output</port>
				</node>
				<node>
					<name>Senke</name>
					<port>Result</port>
				</node>
			</edge>
		</edges>
		<phases>
			<phase nr="1">
					<node>
						<name>Quelle</name>
						<port>
							<name>Output</name>
						</port>
					</node>
					<node>
						<name>Kodierer</name>
						<port>
							<name>Input</name>
						</port>
						<port>
							<name>Output</name>
						</port>
					</node>
					<node>
						<name>Kanal</name>
						<port>
							<name>Input</name>
						</port>
						<port>
							<name>Output</name>
						</port>
					</node>
					<node>
						<name>Dekodierer</name>
						<port>
							<name>Input</name>
						</port>
						<port>
							<name>Output</name>
						</port>
					</node>
					<node>
						<name>Senke</name>
						<observed />
						<port>
							<name>Source</name>
						</port>
						<port>
							<name>Result</name>
						</port>
					</node>
			</phase>
		</phases>
	</graph>
	<settings>
		<default />
		<rounds anz="5">
			<round nr="1" />
			<round nr="2" />
			<round nr="3" />
			<round nr="4" />
			<round nr="5" />
		</rounds>
	</settings>
</simmit:job>
