=== copton/lethe/extensions/modules/Channel/instances/Channel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--generated at: 2006-04-17T19:04:18.413+02:00-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:simmit="https://proj.5nord.org/simmit"
        xmlns:self="https://proj.5nord.org/simmit/modules/Channel"
        targetNamespace="https://proj.5nord.org/simmit/modules/Channel">
   <import namespace="https://proj.5nord.org/simmit"
           schemaLocation="../../../../core/xml/moduleDescription.xsd"/>
   <element name="Channel">
      <complexType>
         <sequence>
            <group ref="self:headerSet"/>
            <element name="include" type="self:include"/>
            <element name="parameter" type="self:parameter"/>
            <element name="ports" type="self:portList"/>
         </sequence>
      </complexType>
   </element>
   <group name="headerSet">
      <sequence>
         <element minOccurs="0" name="author" type="string"/>
         <element minOccurs="0" name="version" type="string"/>
         <element minOccurs="0" name="date" type="date"/>
         <element minOccurs="0" name="type" type="string"/>
         <element minOccurs="0" name="description" type="string"/>
      </sequence>
   </group>
   <complexType name="include">
      <all/>
   </complexType>
   <complexType name="parameter">
      <all>
         <element name="configuration" type="self:configuration"/>
         <element name="settings" type="self:settings"/>
      </all>
   </complexType>
   <complexType name="portList">
      <all>
         <element name="Input" type="simmit:inputPort"/>
         <element name="Output" type="simmit:outputPort"/>
      </all>
   </complexType>
   <complexType name="configuration">
      <all/>
   </complexType>
   <complexType name="settings">
      <all>
         <element name="noiseReal" type="self:Noise"/>
         <element name="noiseImag" type="self:Noise"/>
      </all>
   </complexType>
   <complexType name="Noise">
      <all>
         <element name="period" type="simmit:int"/>
         <element name="amplifier" type="simmit:int"/>
      </all>
      <attribute fixed="class" name="type"/>
      <attribute default="" name="description"/>
      <attribute fixed="Noise" name="classname"/>
   </complexType>
</schema>

=== copton/lethe/extensions/modules/Channel/instances/Channel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--generated at: 2006-04-17T19:04:18.285+02:00-->
<module:Channel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:module="https://proj.5nord.org/simmit/modules/Channel"
                xsi:schemaLocation="https://proj.5nord.org/simmit/modules/Channel Channel.xsd">
   <author>alex</author>
   <version>1.0</version>
   <date>2006-03-06</date>
   <type>Kanal</type>
   <description/>
   <include/>
   <parameter>
      <configuration/>
      <settings>
         <noiseReal type="class" classname="Noise">
            <period type="int">0</period>
            <amplifier type="int">0</amplifier>
         </noiseReal>
         <noiseImag type="class" classname="Noise">
            <period type="int">0</period>
            <amplifier type="int">0</amplifier>
         </noiseImag>
      </settings>
   </parameter>
   <ports>
      <Input direction="input" type="Complex" blocksize="1" usedType="" description=""/>
    
      <Output direction="output" type="Complex" blocksize="1" usedType="" description=""/>
    </ports>
</module:Channel>
